management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    logfile:
      external-file: ./log/info.log
    shutdown:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
    tags:
      application: ${spring.application.name}

## 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
  file:
    path: ./log

# open feign配置
feign:
  # Okhttp参数配置
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    # 默认值
    max-connections: 200
    # 默认值
    max-connections-per-route: 50
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

rocketmq:
  config:
    dataPath: /tmp/rocketmq-console/data
    enableDashBoardCollect: true
    isVIPChannel: ''
    loginRequired: true
    msgTrackTopicName: ''
    namesrvAddr: 47.100.227.235:9876
#    namesrvAddr: 192.168.247.130:9876;192.168.247.131:9876
    ticketKey: ticket


